version: '3.8'
services:
  data_loading:
    build: ./dataset_loading
    ports:
      - "8000:8000"
    volumes:
      - data_volume:/files/

  data_cleaning:
    build: ./data_cleaning
    ports:
      - "8001:8000"
    volumes:
      - data_volume:/files/

  services:
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  data_volume:
