version: '3.8'
services:
  data_loading:
    build: ./backend/microservices/dataset_loading
    ports:
      - "8000:8000"
    volumes:
      - data_volume:/files/

  data_login:
    build: ./backend/microservices/data_login
    ports:
      - "8004:8000"

  data_cleaning:
    build: ./backend/microservices/data_cleaning
    ports:
      - "8001:8000"
    volumes:
      - data_volume:/files/

  frontend:
    build: ./frontend
    ports:
      - "8002:80"

  data_modelling:
    build: ./backend/microservices/data_modelling
    ports:
      - "8003:8000"
    volumes:
      - data_volume:/files/

volumes:
  data_volume:
